apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-px02
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-px02@sha256:7cd283220308dc7f25215cb3dc0fe48762cb3293b4bcceb9d579d23bd4ecd42b
        name: my-nodejs
        resources: {}
status: {}
